config/routes.rb
# == Route Map
#
#    Prefix Verb   URI Pattern               Controller#Action
#      root GET    /                         welcome#index
#   profile GET    /profile(.:format)        welcome#profile
#      tech GET    /tech(.:format)           welcome#tech
#   sign_in GET    /sign_in(.:format)        sessions#new
#           POST   /sign_in(.:format)        sessions#create
#  sign_out DELETE /sign_out(.:format)       sessions#destroy
#     blogs GET    /blogs(.:format)          blogs#index
#           POST   /blogs(.:format)          blogs#create
#  new_blog GET    /blogs/new(.:format)      blogs#new
# edit_blog GET    /blogs/:id/edit(.:format) blogs#edit
#      blog GET    /blogs/:id(.:format)      blogs#show
#           PATCH  /blogs/:id(.:format)      blogs#update
#           PUT    /blogs/:id(.:format)      blogs#update
#           DELETE /blogs/:id(.:format)      blogs#destroy
#

Rails.application.routes.draw do
  root 'welcome#index'
  get 'profile', to: 'welcome#profile'
  get 'tech', to: 'welcome#tech'
  get 'sign_in', to: 'sessions#new'
  post 'sign_in', to: 'sessions#create'
  delete 'sign_out', to: 'sessions#destroy'
  resources :blogs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
# == Schema Information
#
# Table name: blogs
#
#  id         :integer          not null, primary key
#  title      :string
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Blog < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include SessionsHelper

  private

  def sign_in_required
    return if signed_in?
    set_request_from
    redirect_to sign_in_path
  end

  def set_request_from
    session[:request_from] = request.fullpath
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :sign_in_required, only: %i(new create edit update destroy)
  before_action :set_blog, only: %i(show edit update destroy)

  # GET /blogs
  def index
    @blogs = Blog.all
  end

  # GET /blogs/1
  def show
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs
  def create
    @blog = Blog.new(blog_params)

    if @blog.save
      redirect_to @blog, notice: 'Blog was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /blogs/1
  def update
    if @blog.update(blog_params)
      redirect_to @blog, notice: 'Blog was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /blogs/1
  def destroy
    @blog.destroy
    redirect_to blogs_url, notice: 'Blog was successfully destroyed.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    redirect_to root_path if signed_in?
  end

  def create
    if authenticated?(session_param[:password])
      sign_in
      redirect_back_or(root_path)
    else
      render action: :new
    end
  end

  def destroy
    sign_out
    redirect_to root_path
  end

  private

  def session_param
    params.require(:session).permit(:password)
  end

  def redirect_back_or(default)
    redirect_to(session[:request_from] || default)
    session[:request_from] = nil
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def profile
  end

  def tech
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def page_title(title = nil)
    if title.present?
      "#{title} | #{OgiharaRyo::Application.config.title}"
    else
      OgiharaRyo::Application.config.title
    end
  end
end

app/helpers/markdown_helper.rb
module MarkdownHelper
  REDCARPET_OPTIONS = {
    autolink: true,
    space_after_headers: true,
    no_intra_emphasis: true,
    fenced_code_blocks: true,
    tables: true,
    hard_wrap: true,
    xhtml: true,
    lax_html_blocks: true,
    strikethrough: true
  }.freeze

  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language || 'md').div
    end
  end

  def markdown_to_html(md_code)
    html_render = HTMLwithCoderay.new(filter_html: true, hard_wrap: true)
    markdown = Redcarpet::Markdown.new(html_render, REDCARPET_OPTIONS)
    markdown.render(md_code)
  end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in
    session[:signed_in] = true
  end

  def authenticated?(password)
    password == ENV['ADMIN_PASSWORD']
  end

  def signed_in?
    session[:signed_in].present?
  end

  def sign_out
    session[:signed_in] = nil
  end
end

app/views/application/_head.html.slim
title = page_title(yield :title)
meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"
= csrf_meta_tags
= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/application/_header.html.slim
h1 = link_to 'Ogihara Ryo', root_path

nav
  ul
    li = link_to 'Profile', profile_path
    li = link_to 'Blog', blogs_path
    li = link_to 'Tech', tech_path

app/views/blogs/_form.html.slim
= form_for @blog do |f|
  - if @blog.errors.any?
    #error_explanation
      h2 = "#{pluralize(@blog.errors.count, "error")} prohibited this blog from being saved:"
      ul
        - @blog.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :body
    = f.text_area :body
  .actions = f.submit

app/views/blogs/_list.html.slim
#blog_list
  ul
    - Blog.order(created_at: :desc).each do |blog|
      li
        h1 = link_to blog.title, blog_path(blog)
        span.date-time
          | Posted on&nbsp;
          = l blog.created_at

= link_to '新規', new_blog_path if signed_in?

app/views/blogs/edit.html.slim
h1 Editing blog

== render 'form'

= link_to 'Show', @blog
'|
= link_to 'Back', blogs_path

app/views/blogs/index.html.slim
== render 'list'

app/views/blogs/new.html.slim
h1 New blog

== render 'form'

= link_to 'Back', blogs_path

app/views/blogs/show.html.slim
= provide :title, @blog.title

h1 = link_to @blog.title, @blog
span.date-time = l(@blog.created_at)

== markdown_to_html(@blog.body)

p = link_to 'Back', blogs_path
p = link_to '編集', edit_blog_path(@blog) if signed_in?

app/views/layouts/application.html.slim
doctype html
html
  head
    == render 'head'

  body
    header
      == render 'header'

    article
      == yield

app/views/welcome/index.html.slim
== render 'blogs/list'

app/views/welcome/profile.html.slim
= provide :title, 'Profile'

h1 Profile

h2 概要
ul
  li 荻原 涼 (Ogihara Ryo)
  li 1990年10月21生まれ
  li ソフトウェアエンジニア
  li ヘビーゲーマー
  li 福岡県行橋市在宅勤務
  li お仕事ゆるぼ

h2 アカウント
ul
  li = link_to 'Twitter (@OgiharaRyo)', 'https://twitter.com/OgiharaRyo'
  li = link_to 'Facebook', 'https://www.facebook.com/ryo.ogihara.5'
  li = link_to 'GitHub', 'https://github.com/ogihara-ryo'
  li = link_to 'Bitbucket', 'https://bitbucket.org/ogihara-ryo/'
  li = link_to 'GitLab', 'https://gitlab.com/u/ogihara-ryo'

h2 略歴
ul
  li 行橋市立行橋南小学校 (空手極振り)
  li 行橋市立行橋中学校 (ゲーム極振り)
  li 福岡県立苅田工業高等学校 (バンド極振り)
  li
    | (ここまで遊び人)
  li
    | (ここからも遊び人)
  li
    | (2009 〜 2014) 某通信機器システムメーカーの技術開発課、設計課、システム課など
  li
    | (2015) 1年間無職
  li
    | (2016 〜 2017) web 系にキャリアチェンジ(
    = link_to 'フロイデ株式会社', 'http://froide.co.jp'
    | )
  li フリーランス <- 今ここ

h2 技術
h3 今やってる
ul
  li Ruby on Rails (Webシステム、Redmineプラグイン開発など)

h3 過去やってた
ul
  li 組み込みLinux (カーネル、デバイスドライバー、通信プロトコルライブラリ開発など)
  li Linux サウンドプログラミング (ALSA)
  li Windows 通信系アプリケーション (C++ Builder - Embercadero)
  li Android アプリケーション (SIP)
  li Python (人工無脳開発など)

app/views/welcome/tech.html.slim
= provide :title, 'Tech'

h2 Ruby on Rails
ul
  li = link_to 'Redmine プラグイン開発に学ぶパッチング作法(Qiita)', 'http://qiita.com/OgiharaRyo/items/b2ed27d886548fed8864'
  li = link_to 'Rails でシンタックスハイライトに対応した Markdown を書く', 'http://ogihara-ryo.herokuapp.com/blogs/2'